version: "3.7"
services:

  react-app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: react-app
    restart: unless-stopped
    # env_file: .env
    ports:
      - 8080:80
    networks:
      - react

networks:
  react:
    driver: bridge